### PR TITLE
create domains table

### PR DESCRIPTION
**Pull request by pytlesk4**
[domains model](https://next.stoplight.io/stoplight/next-api/blob/master/domains.oas2.yml?view=/models/domain-output)

### CODE REVIEW

**Comment by pytlesk4** [comment]
Migrated successfully

**Review by rainum — COMMENTED** [review]
Looks good to me 👍

**Comment by pytlesk4** [comment]
@marbemac can I merge this?

**Review by marbemac — DISMISSED** [review]
Remove index on active_build_id and we're good. There's no querying that needs to be done on that column - it'll be the left side of a join and don't need a where on it.

**Comment by pytlesk4** [comment]
> Remove index on active_build_id and we're good. There's no querying that needs to be done on that column - it'll be the left side of a join and don't need a where on it.

Removed

**Pull request merged**
