### PR TITLE
SL-1263: created migration and rollback for discovery tables

### PR DESCRIPTION
**Pull request by chohmann**
Migration and rollback for discovery tables.

### CODE REVIEW

**Comment by rossmcdonald** [comment]
@chohmann Any chance we could move all of the `TRIGGER`/`FUNCTION` logic into the application layer? The `TRIGGER`/`FUNCTION` stuff that we have already defined wreak havoc on our customer sites because they are outside the Rails ORM and are not (typically) run by default as part of the usual migration. 

We have an issue that I made a while back that goes through the issues: https://stoplightio.atlassian.net/browse/SL-655

I'm also open to someone spending more time in becoming an ActiveRecord expert to figure out how to reliably run these migrations, but we should hold off on adding more until we figure it out. We may also want to use this as an opportunity for investigating how to manage our own migrations outside of GitLab.

**Comment by chohmann** [comment]
@rossmcdonald the dates are handled in the db using triggers, because Graphql doesn't have a Date type defined out of the box so all of these properties are defined as strings in the API. Creating a date and converting it to a String fails upon trying to insert into the Postgres db date field. When speaking to Tom on this, he said for all other dates used in our API they have opted for the db to handle it. 

So I think the options we have are:
1.  invest time into solving the Date type in GraphQL by creating a custom scalar
2. move our migrations into something other than gitlab (planned)

I spoke to @brianmrock about changing migration strategies earlier today, and there is already plans for removing the gitlab dependency. I'll let him speak to the timeline on that. 

But since there are already plans for solving this, we decided to just go ahead and use gitlab for these discovery migrations, and they'll be migrated (😉) to whatever strategy is decided upon, and therefore solving the the trigger issues.

@brianmrock can you speak to these points in a bit more detail?

**Comment by pytlesk4** [comment]
I think there might be some confusing around dates, and I am sorry that I probably added to it. I was up pretty late last night so I don't remember anything. If this is causing havoc for on-prem installs, it shouldn't be hard to support this in the API. 

I don't think we will need to add a custom scalar type, and there probably is an open source date scalar on github already. In the graphql api we can just represent dates as strings, and then before we insert it into the DB we can transform the string to a date, or whatever postgres needs with a transformer. Similar to what we do with doc configs [here](https://github.com/stoplightio/api/blob/develop/src/services/docs/model.ts#L223-L224).

Sorry about the confusion guys. Typeorm does have really good support for migrations, so it might be really easy to move over to that as well.

**Comment by rossmcdonald** [comment]
@pytlesk4 Thanks for the context. We can stick with this for now since we already have to these postgres-specific sections in there. We just have seen _a lot_ of issues with customers where the migrations aren't run properly (or are only partially run) and I have never really been able to figure out why or how to properly fix it. I think we should switch to managing our own migrations ASAP since no one seems to really know why ActiveRecord does what it does.

We're also falling further and further behind upstream GitLab, so the sooner we can break away from GitLab stuff the better.

**Comment by pytlesk4** [comment]
@chohmann Also, a quick search of dates found a way to add [Dates](https://www.apollographql.com/docs/apollo-server/features/scalars-enums.html#Date-as-a-scalar)

**Comment by chohmann** [comment]
Yeah I found that page too! So we just have to decide if that's the route we want to go, or wait until the "get off gitlab" stuff happens. Changing the migration strategy was going to be a part of that initiative, from what I understand, so this issue will be gone with that work. I think @brianmrock has a good idea on realistic timeline for getting off of gitlab, and that will help us determine what steps to take.

**Comment by brianmrock** [comment]
Yeah, we are doing the design spike on the gitlab dependency removal this sprint.  Part of that plan will be to come up with a new DB migration tool.  So, let's just deal with this for now and we will address the problem @rossmcdonald stated when we change migration strategies.

**Review by pytlesk4 — DISMISSED** [review]
This looks good to me, let's wait on merging this just in case anything changes. But approving so that we can merge before sprint demo.

**Comment by pytlesk4** [comment]
@chohmann if a project is deleted, should we clean up repos? If so, we need to cascade on deletion of project. Going to look at the other FKs.

**Comment by chohmann** [comment]
I guess that’s the case, but if you delete the repo, you’re gonna have to delete the branches, commits, commit branches, nodes, node history, node edges, node history validations. Pretty much everything for that repo.

**Comment by pytlesk4** [comment]
> I guess that’s the case, but if you delete the repo, you’re gonna have to delete the branches, commits, commit branches, nodes, node history, node edges, node history validations. Pretty much everything for that repo.

If we set up FKs correctly, it should clean up just fine for all those tables! I think that it makes sense to do that. 

For example, 

1. My repo lives at github.com/tom/foo, and I configure a stoplight project to analyze it, and history is generated.
2. Eventually delete I delete my stoplight project, then delete github.com/tom/foo from github.
3. Eventually create a new repo at github.com/tom/foo(same repo location, but not related to what was there previously), and repeat step 1.

If we don't clean up the db properly, then I will see a bunch of old history that doesn't make sense anymore.

**Review by pytlesk4 — APPROVED** [review]

**Pull request merged**
