### PR TITLE
fix: add migration to change namespace_tag namespace_id SL-2642

### PR DESCRIPTION
**Pull request by rainum**
This PR adds a data migration to change namespace_tag namespace_id from a user id to an actual namespace id.

https://stoplightio.atlassian.net/browse/SL-2642

### CODE REVIEW

**Comment by chohmann** [comment]
This LGTM. However @collinbachi are we still creating the migrations here? Or do they need to be created in that new tool? I can't remember where we ended up with this.

**Comment by collinbachi** [comment]
In the new tool, since we don’t deploy gitlab anymore

**Comment by rainum** [comment]
@collinbachi @chohmann could you guys point me to a some example of a new tool migration?

**Comment by chohmann** [comment]
Yeah I believe you add the new migrations to here: https://github.com/stoplightio/migrations/tree/master/migrate/db/migrate

@collinbachi, please correct me if I'm wrong.

**Comment by rainum** [comment]
Ah got it, this a repo @rossmcdonald create for a standalone activerecord migrations, right?

**Comment by collinbachi** [comment]
Right. If you look at the migrations in there, you'll see you can basically copy and paste. You just have to remove a few gitlab-specific library references

**Comment by rainum** [comment]
Yeah, got it! I forgot about migrations repo, my bad. I'll close this PR and reopen it at https://github.com/stoplightio/migrations

**Pull request closed without merging**
